import os

generated_header = "src/build_info.h"
contents = f"""
// Copyright (C) 2025 Austen Danger Bartels - All Rights Reserved
// You may use, distribute and modify this code under the
// terms of the CC BY-NC-SA license.
//
// You should have received a copy of the CC BY-NC-SA license with
// this file. If not, please visit : github.com/millibyte/candrive-fw

// !!!GENERATED FILE!!!
// DO NOT EDIT, generated by build_info.py

#ifndef _BUILD_INFO_H_
#define _BUILD_INFO_H_

const uint8_t GIT_SHA[21] PROGMEM = {{
    {os.system("echo -n $(git rev-parse HEAD) | xxd -p -c 1024 | sed 's/../0x&, /g'")}, 0x00
}};
const uint32_t FW_VER PROGMEM = VERSION_MAJOR << 16 | VERSION_MINOR << 8 | VERSION_PATCH;
const uint64_t BUILD_TIMESTAMP PROGMEM = {os.system("date +%s")};
const uint8_t PROTOCOL_VER PROGMEM = 1;

#endif // _BUILD_INFO_H_

"""

with open(generated_header, "w") as f:
    f.write(contents)
