[package]
name    = "candrive-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "app"
path = "src/main.rs"

[dependencies]
candrive-shared = { path = "../shared" }
cortex-m        = "0.7"
cortex-m-rt     = "0.7"
panic-halt      = "1.0"
stm32f1         = { version = "0.15", features = ["stm32f103", "rt"] }
libm            = "0.2"
